version: "3.8"

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${DB_HOST:-127.0.0.1}
      PMA_PORT: ${DB_PORT:-3306}
      PMA_USER: ${DB_USER:-podjdr}
      PMA_PASSWORD: ${DB_PASSWORD:-podmdp}
